// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/Debug/Debug.proto

package fr.kissy.banshee.proto;

public final class DebugDTO {
  private DebugDTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DebugProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .DebugEntityProto entities = 1;
    java.util.List<fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto> 
        getEntitiesList();
    fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto getEntities(int index);
    int getEntitiesCount();
    java.util.List<? extends fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProtoOrBuilder> 
        getEntitiesOrBuilderList();
    fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProtoOrBuilder getEntitiesOrBuilder(
        int index);
  }
  public static final class DebugProto extends
      com.google.protobuf.GeneratedMessage
      implements DebugProtoOrBuilder {
    // Use DebugProto.newBuilder() to construct.
    private DebugProto(Builder builder) {
      super(builder);
    }
    private DebugProto(boolean noInit) {}
    
    private static final DebugProto defaultInstance;
    public static DebugProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public DebugProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.kissy.banshee.proto.DebugDTO.internal_static_DebugProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.kissy.banshee.proto.DebugDTO.internal_static_DebugProto_fieldAccessorTable;
    }
    
    // repeated .DebugEntityProto entities = 1;
    public static final int ENTITIES_FIELD_NUMBER = 1;
    private java.util.List<fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto> entities_;
    public java.util.List<fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto> getEntitiesList() {
      return entities_;
    }
    public java.util.List<? extends fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProtoOrBuilder> 
        getEntitiesOrBuilderList() {
      return entities_;
    }
    public int getEntitiesCount() {
      return entities_.size();
    }
    public fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto getEntities(int index) {
      return entities_.get(index);
    }
    public fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProtoOrBuilder getEntitiesOrBuilder(
        int index) {
      return entities_.get(index);
    }
    
    private void initFields() {
      entities_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getEntitiesCount(); i++) {
        if (!getEntities(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < entities_.size(); i++) {
        output.writeMessage(1, entities_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < entities_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, entities_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static fr.kissy.banshee.proto.DebugDTO.DebugProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static fr.kissy.banshee.proto.DebugDTO.DebugProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static fr.kissy.banshee.proto.DebugDTO.DebugProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static fr.kissy.banshee.proto.DebugDTO.DebugProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static fr.kissy.banshee.proto.DebugDTO.DebugProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static fr.kissy.banshee.proto.DebugDTO.DebugProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static fr.kissy.banshee.proto.DebugDTO.DebugProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static fr.kissy.banshee.proto.DebugDTO.DebugProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static fr.kissy.banshee.proto.DebugDTO.DebugProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static fr.kissy.banshee.proto.DebugDTO.DebugProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fr.kissy.banshee.proto.DebugDTO.DebugProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements fr.kissy.banshee.proto.DebugDTO.DebugProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.kissy.banshee.proto.DebugDTO.internal_static_DebugProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.kissy.banshee.proto.DebugDTO.internal_static_DebugProto_fieldAccessorTable;
      }
      
      // Construct using fr.kissy.banshee.proto.DebugDTO.DebugProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEntitiesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (entitiesBuilder_ == null) {
          entities_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          entitiesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fr.kissy.banshee.proto.DebugDTO.DebugProto.getDescriptor();
      }
      
      public fr.kissy.banshee.proto.DebugDTO.DebugProto getDefaultInstanceForType() {
        return fr.kissy.banshee.proto.DebugDTO.DebugProto.getDefaultInstance();
      }
      
      public fr.kissy.banshee.proto.DebugDTO.DebugProto build() {
        fr.kissy.banshee.proto.DebugDTO.DebugProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private fr.kissy.banshee.proto.DebugDTO.DebugProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        fr.kissy.banshee.proto.DebugDTO.DebugProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public fr.kissy.banshee.proto.DebugDTO.DebugProto buildPartial() {
        fr.kissy.banshee.proto.DebugDTO.DebugProto result = new fr.kissy.banshee.proto.DebugDTO.DebugProto(this);
        int from_bitField0_ = bitField0_;
        if (entitiesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            entities_ = java.util.Collections.unmodifiableList(entities_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.entities_ = entities_;
        } else {
          result.entities_ = entitiesBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fr.kissy.banshee.proto.DebugDTO.DebugProto) {
          return mergeFrom((fr.kissy.banshee.proto.DebugDTO.DebugProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(fr.kissy.banshee.proto.DebugDTO.DebugProto other) {
        if (other == fr.kissy.banshee.proto.DebugDTO.DebugProto.getDefaultInstance()) return this;
        if (entitiesBuilder_ == null) {
          if (!other.entities_.isEmpty()) {
            if (entities_.isEmpty()) {
              entities_ = other.entities_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEntitiesIsMutable();
              entities_.addAll(other.entities_);
            }
            onChanged();
          }
        } else {
          if (!other.entities_.isEmpty()) {
            if (entitiesBuilder_.isEmpty()) {
              entitiesBuilder_.dispose();
              entitiesBuilder_ = null;
              entities_ = other.entities_;
              bitField0_ = (bitField0_ & ~0x00000001);
              entitiesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEntitiesFieldBuilder() : null;
            } else {
              entitiesBuilder_.addAllMessages(other.entities_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getEntitiesCount(); i++) {
          if (!getEntities(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto.Builder subBuilder = fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addEntities(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .DebugEntityProto entities = 1;
      private java.util.List<fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto> entities_ =
        java.util.Collections.emptyList();
      private void ensureEntitiesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          entities_ = new java.util.ArrayList<fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto>(entities_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto, fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto.Builder, fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProtoOrBuilder> entitiesBuilder_;
      
      public java.util.List<fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto> getEntitiesList() {
        if (entitiesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(entities_);
        } else {
          return entitiesBuilder_.getMessageList();
        }
      }
      public int getEntitiesCount() {
        if (entitiesBuilder_ == null) {
          return entities_.size();
        } else {
          return entitiesBuilder_.getCount();
        }
      }
      public fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto getEntities(int index) {
        if (entitiesBuilder_ == null) {
          return entities_.get(index);
        } else {
          return entitiesBuilder_.getMessage(index);
        }
      }
      public Builder setEntities(
          int index, fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto value) {
        if (entitiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntitiesIsMutable();
          entities_.set(index, value);
          onChanged();
        } else {
          entitiesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setEntities(
          int index, fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto.Builder builderForValue) {
        if (entitiesBuilder_ == null) {
          ensureEntitiesIsMutable();
          entities_.set(index, builderForValue.build());
          onChanged();
        } else {
          entitiesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addEntities(fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto value) {
        if (entitiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntitiesIsMutable();
          entities_.add(value);
          onChanged();
        } else {
          entitiesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addEntities(
          int index, fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto value) {
        if (entitiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntitiesIsMutable();
          entities_.add(index, value);
          onChanged();
        } else {
          entitiesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addEntities(
          fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto.Builder builderForValue) {
        if (entitiesBuilder_ == null) {
          ensureEntitiesIsMutable();
          entities_.add(builderForValue.build());
          onChanged();
        } else {
          entitiesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addEntities(
          int index, fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto.Builder builderForValue) {
        if (entitiesBuilder_ == null) {
          ensureEntitiesIsMutable();
          entities_.add(index, builderForValue.build());
          onChanged();
        } else {
          entitiesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllEntities(
          java.lang.Iterable<? extends fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto> values) {
        if (entitiesBuilder_ == null) {
          ensureEntitiesIsMutable();
          super.addAll(values, entities_);
          onChanged();
        } else {
          entitiesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearEntities() {
        if (entitiesBuilder_ == null) {
          entities_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          entitiesBuilder_.clear();
        }
        return this;
      }
      public Builder removeEntities(int index) {
        if (entitiesBuilder_ == null) {
          ensureEntitiesIsMutable();
          entities_.remove(index);
          onChanged();
        } else {
          entitiesBuilder_.remove(index);
        }
        return this;
      }
      public fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto.Builder getEntitiesBuilder(
          int index) {
        return getEntitiesFieldBuilder().getBuilder(index);
      }
      public fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProtoOrBuilder getEntitiesOrBuilder(
          int index) {
        if (entitiesBuilder_ == null) {
          return entities_.get(index);  } else {
          return entitiesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProtoOrBuilder> 
           getEntitiesOrBuilderList() {
        if (entitiesBuilder_ != null) {
          return entitiesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(entities_);
        }
      }
      public fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto.Builder addEntitiesBuilder() {
        return getEntitiesFieldBuilder().addBuilder(
            fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto.getDefaultInstance());
      }
      public fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto.Builder addEntitiesBuilder(
          int index) {
        return getEntitiesFieldBuilder().addBuilder(
            index, fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto.getDefaultInstance());
      }
      public java.util.List<fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto.Builder> 
           getEntitiesBuilderList() {
        return getEntitiesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto, fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto.Builder, fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProtoOrBuilder> 
          getEntitiesFieldBuilder() {
        if (entitiesBuilder_ == null) {
          entitiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto, fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProto.Builder, fr.kissy.banshee.proto.DebugEntityDTO.DebugEntityProtoOrBuilder>(
                  entities_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          entities_ = null;
        }
        return entitiesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:DebugProto)
    }
    
    static {
      defaultInstance = new DebugProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:DebugProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DebugProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DebugProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027Proto/Debug/Debug.proto\032\035Proto/Debug/D" +
      "ebugEntity.proto\"1\n\nDebugProto\022#\n\010entiti" +
      "es\030\001 \003(\0132\021.DebugEntityProtoB%\n\026fr.kissy." +
      "banshee.protoB\010DebugDTO\210\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_DebugProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_DebugProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DebugProto_descriptor,
              new java.lang.String[] { "Entities", },
              fr.kissy.banshee.proto.DebugDTO.DebugProto.class,
              fr.kissy.banshee.proto.DebugDTO.DebugProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          fr.kissy.banshee.proto.DebugEntityDTO.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
