// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/Debug/DebugProperty.proto

package fr.kissy.banshee.proto;

public final class DebugPropertyDTO {
  private DebugPropertyDTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DebugPropertyProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string category = 1 [default = "default"];
    /**
     * <code>optional string category = 1 [default = "default"];</code>
     */
    boolean hasCategory();
    /**
     * <code>optional string category = 1 [default = "default"];</code>
     */
    java.lang.String getCategory();
    /**
     * <code>optional string category = 1 [default = "default"];</code>
     */
    com.google.protobuf.ByteString
        getCategoryBytes();

    // repeated .Proto.Property properties = 2;
    /**
     * <code>repeated .Proto.Property properties = 2;</code>
     */
    java.util.List<fr.kissy.hellion.proto.Common.Property> 
        getPropertiesList();
    /**
     * <code>repeated .Proto.Property properties = 2;</code>
     */
    fr.kissy.hellion.proto.Common.Property getProperties(int index);
    /**
     * <code>repeated .Proto.Property properties = 2;</code>
     */
    int getPropertiesCount();
    /**
     * <code>repeated .Proto.Property properties = 2;</code>
     */
    java.util.List<? extends fr.kissy.hellion.proto.Common.PropertyOrBuilder> 
        getPropertiesOrBuilderList();
    /**
     * <code>repeated .Proto.Property properties = 2;</code>
     */
    fr.kissy.hellion.proto.Common.PropertyOrBuilder getPropertiesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DebugPropertyProto}
   */
  public static final class DebugPropertyProto extends
      com.google.protobuf.GeneratedMessage
      implements DebugPropertyProtoOrBuilder {
    // Use DebugPropertyProto.newBuilder() to construct.
    private DebugPropertyProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DebugPropertyProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DebugPropertyProto defaultInstance;
    public static DebugPropertyProto getDefaultInstance() {
      return defaultInstance;
    }

    public DebugPropertyProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DebugPropertyProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              category_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                properties_ = new java.util.ArrayList<fr.kissy.hellion.proto.Common.Property>();
                mutable_bitField0_ |= 0x00000002;
              }
              properties_.add(input.readMessage(fr.kissy.hellion.proto.Common.Property.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          properties_ = java.util.Collections.unmodifiableList(properties_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.kissy.banshee.proto.DebugPropertyDTO.internal_static_DebugPropertyProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.kissy.banshee.proto.DebugPropertyDTO.internal_static_DebugPropertyProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto.class, fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto.Builder.class);
    }

    public static com.google.protobuf.Parser<DebugPropertyProto> PARSER =
        new com.google.protobuf.AbstractParser<DebugPropertyProto>() {
      public DebugPropertyProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DebugPropertyProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DebugPropertyProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string category = 1 [default = "default"];
    public static final int CATEGORY_FIELD_NUMBER = 1;
    private java.lang.Object category_;
    /**
     * <code>optional string category = 1 [default = "default"];</code>
     */
    public boolean hasCategory() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string category = 1 [default = "default"];</code>
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          category_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string category = 1 [default = "default"];</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .Proto.Property properties = 2;
    public static final int PROPERTIES_FIELD_NUMBER = 2;
    private java.util.List<fr.kissy.hellion.proto.Common.Property> properties_;
    /**
     * <code>repeated .Proto.Property properties = 2;</code>
     */
    public java.util.List<fr.kissy.hellion.proto.Common.Property> getPropertiesList() {
      return properties_;
    }
    /**
     * <code>repeated .Proto.Property properties = 2;</code>
     */
    public java.util.List<? extends fr.kissy.hellion.proto.Common.PropertyOrBuilder> 
        getPropertiesOrBuilderList() {
      return properties_;
    }
    /**
     * <code>repeated .Proto.Property properties = 2;</code>
     */
    public int getPropertiesCount() {
      return properties_.size();
    }
    /**
     * <code>repeated .Proto.Property properties = 2;</code>
     */
    public fr.kissy.hellion.proto.Common.Property getProperties(int index) {
      return properties_.get(index);
    }
    /**
     * <code>repeated .Proto.Property properties = 2;</code>
     */
    public fr.kissy.hellion.proto.Common.PropertyOrBuilder getPropertiesOrBuilder(
        int index) {
      return properties_.get(index);
    }

    private void initFields() {
      category_ = "default";
      properties_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getPropertiesCount(); i++) {
        if (!getProperties(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCategoryBytes());
      }
      for (int i = 0; i < properties_.size(); i++) {
        output.writeMessage(2, properties_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCategoryBytes());
      }
      for (int i = 0; i < properties_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, properties_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DebugPropertyProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.kissy.banshee.proto.DebugPropertyDTO.internal_static_DebugPropertyProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.kissy.banshee.proto.DebugPropertyDTO.internal_static_DebugPropertyProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto.class, fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto.Builder.class);
      }

      // Construct using fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPropertiesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        category_ = "default";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (propertiesBuilder_ == null) {
          properties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          propertiesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fr.kissy.banshee.proto.DebugPropertyDTO.internal_static_DebugPropertyProto_descriptor;
      }

      public fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto getDefaultInstanceForType() {
        return fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto.getDefaultInstance();
      }

      public fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto build() {
        fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto buildPartial() {
        fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto result = new fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.category_ = category_;
        if (propertiesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            properties_ = java.util.Collections.unmodifiableList(properties_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.properties_ = properties_;
        } else {
          result.properties_ = propertiesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto) {
          return mergeFrom((fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto other) {
        if (other == fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto.getDefaultInstance()) return this;
        if (other.hasCategory()) {
          bitField0_ |= 0x00000001;
          category_ = other.category_;
          onChanged();
        }
        if (propertiesBuilder_ == null) {
          if (!other.properties_.isEmpty()) {
            if (properties_.isEmpty()) {
              properties_ = other.properties_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePropertiesIsMutable();
              properties_.addAll(other.properties_);
            }
            onChanged();
          }
        } else {
          if (!other.properties_.isEmpty()) {
            if (propertiesBuilder_.isEmpty()) {
              propertiesBuilder_.dispose();
              propertiesBuilder_ = null;
              properties_ = other.properties_;
              bitField0_ = (bitField0_ & ~0x00000002);
              propertiesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPropertiesFieldBuilder() : null;
            } else {
              propertiesBuilder_.addAllMessages(other.properties_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPropertiesCount(); i++) {
          if (!getProperties(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fr.kissy.banshee.proto.DebugPropertyDTO.DebugPropertyProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string category = 1 [default = "default"];
      private java.lang.Object category_ = "default";
      /**
       * <code>optional string category = 1 [default = "default"];</code>
       */
      public boolean hasCategory() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string category = 1 [default = "default"];</code>
       */
      public java.lang.String getCategory() {
        java.lang.Object ref = category_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          category_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string category = 1 [default = "default"];</code>
       */
      public com.google.protobuf.ByteString
          getCategoryBytes() {
        java.lang.Object ref = category_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          category_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string category = 1 [default = "default"];</code>
       */
      public Builder setCategory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string category = 1 [default = "default"];</code>
       */
      public Builder clearCategory() {
        bitField0_ = (bitField0_ & ~0x00000001);
        category_ = getDefaultInstance().getCategory();
        onChanged();
        return this;
      }
      /**
       * <code>optional string category = 1 [default = "default"];</code>
       */
      public Builder setCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        category_ = value;
        onChanged();
        return this;
      }

      // repeated .Proto.Property properties = 2;
      private java.util.List<fr.kissy.hellion.proto.Common.Property> properties_ =
        java.util.Collections.emptyList();
      private void ensurePropertiesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          properties_ = new java.util.ArrayList<fr.kissy.hellion.proto.Common.Property>(properties_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          fr.kissy.hellion.proto.Common.Property, fr.kissy.hellion.proto.Common.Property.Builder, fr.kissy.hellion.proto.Common.PropertyOrBuilder> propertiesBuilder_;

      /**
       * <code>repeated .Proto.Property properties = 2;</code>
       */
      public java.util.List<fr.kissy.hellion.proto.Common.Property> getPropertiesList() {
        if (propertiesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(properties_);
        } else {
          return propertiesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Proto.Property properties = 2;</code>
       */
      public int getPropertiesCount() {
        if (propertiesBuilder_ == null) {
          return properties_.size();
        } else {
          return propertiesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Proto.Property properties = 2;</code>
       */
      public fr.kissy.hellion.proto.Common.Property getProperties(int index) {
        if (propertiesBuilder_ == null) {
          return properties_.get(index);
        } else {
          return propertiesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Proto.Property properties = 2;</code>
       */
      public Builder setProperties(
          int index, fr.kissy.hellion.proto.Common.Property value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.set(index, value);
          onChanged();
        } else {
          propertiesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Proto.Property properties = 2;</code>
       */
      public Builder setProperties(
          int index, fr.kissy.hellion.proto.Common.Property.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.set(index, builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Proto.Property properties = 2;</code>
       */
      public Builder addProperties(fr.kissy.hellion.proto.Common.Property value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.add(value);
          onChanged();
        } else {
          propertiesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Proto.Property properties = 2;</code>
       */
      public Builder addProperties(
          int index, fr.kissy.hellion.proto.Common.Property value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertiesIsMutable();
          properties_.add(index, value);
          onChanged();
        } else {
          propertiesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Proto.Property properties = 2;</code>
       */
      public Builder addProperties(
          fr.kissy.hellion.proto.Common.Property.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.add(builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Proto.Property properties = 2;</code>
       */
      public Builder addProperties(
          int index, fr.kissy.hellion.proto.Common.Property.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.add(index, builderForValue.build());
          onChanged();
        } else {
          propertiesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Proto.Property properties = 2;</code>
       */
      public Builder addAllProperties(
          java.lang.Iterable<? extends fr.kissy.hellion.proto.Common.Property> values) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          super.addAll(values, properties_);
          onChanged();
        } else {
          propertiesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Proto.Property properties = 2;</code>
       */
      public Builder clearProperties() {
        if (propertiesBuilder_ == null) {
          properties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          propertiesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Proto.Property properties = 2;</code>
       */
      public Builder removeProperties(int index) {
        if (propertiesBuilder_ == null) {
          ensurePropertiesIsMutable();
          properties_.remove(index);
          onChanged();
        } else {
          propertiesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Proto.Property properties = 2;</code>
       */
      public fr.kissy.hellion.proto.Common.Property.Builder getPropertiesBuilder(
          int index) {
        return getPropertiesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Proto.Property properties = 2;</code>
       */
      public fr.kissy.hellion.proto.Common.PropertyOrBuilder getPropertiesOrBuilder(
          int index) {
        if (propertiesBuilder_ == null) {
          return properties_.get(index);  } else {
          return propertiesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Proto.Property properties = 2;</code>
       */
      public java.util.List<? extends fr.kissy.hellion.proto.Common.PropertyOrBuilder> 
           getPropertiesOrBuilderList() {
        if (propertiesBuilder_ != null) {
          return propertiesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(properties_);
        }
      }
      /**
       * <code>repeated .Proto.Property properties = 2;</code>
       */
      public fr.kissy.hellion.proto.Common.Property.Builder addPropertiesBuilder() {
        return getPropertiesFieldBuilder().addBuilder(
            fr.kissy.hellion.proto.Common.Property.getDefaultInstance());
      }
      /**
       * <code>repeated .Proto.Property properties = 2;</code>
       */
      public fr.kissy.hellion.proto.Common.Property.Builder addPropertiesBuilder(
          int index) {
        return getPropertiesFieldBuilder().addBuilder(
            index, fr.kissy.hellion.proto.Common.Property.getDefaultInstance());
      }
      /**
       * <code>repeated .Proto.Property properties = 2;</code>
       */
      public java.util.List<fr.kissy.hellion.proto.Common.Property.Builder> 
           getPropertiesBuilderList() {
        return getPropertiesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          fr.kissy.hellion.proto.Common.Property, fr.kissy.hellion.proto.Common.Property.Builder, fr.kissy.hellion.proto.Common.PropertyOrBuilder> 
          getPropertiesFieldBuilder() {
        if (propertiesBuilder_ == null) {
          propertiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              fr.kissy.hellion.proto.Common.Property, fr.kissy.hellion.proto.Common.Property.Builder, fr.kissy.hellion.proto.Common.PropertyOrBuilder>(
                  properties_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          properties_ = null;
        }
        return propertiesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:DebugPropertyProto)
    }

    static {
      defaultInstance = new DebugPropertyProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DebugPropertyProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DebugPropertyProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DebugPropertyProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037Proto/Debug/DebugProperty.proto\032\022Proto" +
      "/Common.proto\"T\n\022DebugPropertyProto\022\031\n\010c" +
      "ategory\030\001 \001(\t:\007default\022#\n\nproperties\030\002 \003" +
      "(\0132\017.Proto.PropertyB-\n\026fr.kissy.banshee." +
      "protoB\020DebugPropertyDTO\210\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_DebugPropertyProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_DebugPropertyProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DebugPropertyProto_descriptor,
              new java.lang.String[] { "Category", "Properties", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          fr.kissy.hellion.proto.Common.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
