// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/Debug/Object.proto

package fr.kissy.banshee.proto;

public final class ObjectDTO {
  private ObjectDTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ObjectProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // required string name = 2;
    boolean hasName();
    String getName();
    
    // optional string category = 3 [default = "default"];
    boolean hasCategory();
    String getCategory();
    
    // repeated .ObjectPropertyProto objectProperties = 4;
    java.util.List<fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto> 
        getObjectPropertiesList();
    fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto getObjectProperties(int index);
    int getObjectPropertiesCount();
    java.util.List<? extends fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProtoOrBuilder> 
        getObjectPropertiesOrBuilderList();
    fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProtoOrBuilder getObjectPropertiesOrBuilder(
        int index);
  }
  public static final class ObjectProto extends
      com.google.protobuf.GeneratedMessage
      implements ObjectProtoOrBuilder {
    // Use ObjectProto.newBuilder() to construct.
    private ObjectProto(Builder builder) {
      super(builder);
    }
    private ObjectProto(boolean noInit) {}
    
    private static final ObjectProto defaultInstance;
    public static ObjectProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public ObjectProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.kissy.banshee.proto.ObjectDTO.internal_static_ObjectProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.kissy.banshee.proto.ObjectDTO.internal_static_ObjectProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string category = 3 [default = "default"];
    public static final int CATEGORY_FIELD_NUMBER = 3;
    private java.lang.Object category_;
    public boolean hasCategory() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getCategory() {
      java.lang.Object ref = category_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          category_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .ObjectPropertyProto objectProperties = 4;
    public static final int OBJECTPROPERTIES_FIELD_NUMBER = 4;
    private java.util.List<fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto> objectProperties_;
    public java.util.List<fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto> getObjectPropertiesList() {
      return objectProperties_;
    }
    public java.util.List<? extends fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProtoOrBuilder> 
        getObjectPropertiesOrBuilderList() {
      return objectProperties_;
    }
    public int getObjectPropertiesCount() {
      return objectProperties_.size();
    }
    public fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto getObjectProperties(int index) {
      return objectProperties_.get(index);
    }
    public fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProtoOrBuilder getObjectPropertiesOrBuilder(
        int index) {
      return objectProperties_.get(index);
    }
    
    private void initFields() {
      id_ = "";
      name_ = "";
      category_ = "default";
      objectProperties_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getObjectPropertiesCount(); i++) {
        if (!getObjectProperties(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCategoryBytes());
      }
      for (int i = 0; i < objectProperties_.size(); i++) {
        output.writeMessage(4, objectProperties_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCategoryBytes());
      }
      for (int i = 0; i < objectProperties_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, objectProperties_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static fr.kissy.banshee.proto.ObjectDTO.ObjectProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static fr.kissy.banshee.proto.ObjectDTO.ObjectProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static fr.kissy.banshee.proto.ObjectDTO.ObjectProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static fr.kissy.banshee.proto.ObjectDTO.ObjectProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static fr.kissy.banshee.proto.ObjectDTO.ObjectProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static fr.kissy.banshee.proto.ObjectDTO.ObjectProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static fr.kissy.banshee.proto.ObjectDTO.ObjectProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static fr.kissy.banshee.proto.ObjectDTO.ObjectProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static fr.kissy.banshee.proto.ObjectDTO.ObjectProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static fr.kissy.banshee.proto.ObjectDTO.ObjectProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fr.kissy.banshee.proto.ObjectDTO.ObjectProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements fr.kissy.banshee.proto.ObjectDTO.ObjectProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.kissy.banshee.proto.ObjectDTO.internal_static_ObjectProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.kissy.banshee.proto.ObjectDTO.internal_static_ObjectProto_fieldAccessorTable;
      }
      
      // Construct using fr.kissy.banshee.proto.ObjectDTO.ObjectProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getObjectPropertiesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        category_ = "default";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (objectPropertiesBuilder_ == null) {
          objectProperties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          objectPropertiesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fr.kissy.banshee.proto.ObjectDTO.ObjectProto.getDescriptor();
      }
      
      public fr.kissy.banshee.proto.ObjectDTO.ObjectProto getDefaultInstanceForType() {
        return fr.kissy.banshee.proto.ObjectDTO.ObjectProto.getDefaultInstance();
      }
      
      public fr.kissy.banshee.proto.ObjectDTO.ObjectProto build() {
        fr.kissy.banshee.proto.ObjectDTO.ObjectProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private fr.kissy.banshee.proto.ObjectDTO.ObjectProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        fr.kissy.banshee.proto.ObjectDTO.ObjectProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public fr.kissy.banshee.proto.ObjectDTO.ObjectProto buildPartial() {
        fr.kissy.banshee.proto.ObjectDTO.ObjectProto result = new fr.kissy.banshee.proto.ObjectDTO.ObjectProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.category_ = category_;
        if (objectPropertiesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            objectProperties_ = java.util.Collections.unmodifiableList(objectProperties_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.objectProperties_ = objectProperties_;
        } else {
          result.objectProperties_ = objectPropertiesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fr.kissy.banshee.proto.ObjectDTO.ObjectProto) {
          return mergeFrom((fr.kissy.banshee.proto.ObjectDTO.ObjectProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(fr.kissy.banshee.proto.ObjectDTO.ObjectProto other) {
        if (other == fr.kissy.banshee.proto.ObjectDTO.ObjectProto.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasCategory()) {
          setCategory(other.getCategory());
        }
        if (objectPropertiesBuilder_ == null) {
          if (!other.objectProperties_.isEmpty()) {
            if (objectProperties_.isEmpty()) {
              objectProperties_ = other.objectProperties_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureObjectPropertiesIsMutable();
              objectProperties_.addAll(other.objectProperties_);
            }
            onChanged();
          }
        } else {
          if (!other.objectProperties_.isEmpty()) {
            if (objectPropertiesBuilder_.isEmpty()) {
              objectPropertiesBuilder_.dispose();
              objectPropertiesBuilder_ = null;
              objectProperties_ = other.objectProperties_;
              bitField0_ = (bitField0_ & ~0x00000008);
              objectPropertiesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getObjectPropertiesFieldBuilder() : null;
            } else {
              objectPropertiesBuilder_.addAllMessages(other.objectProperties_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        for (int i = 0; i < getObjectPropertiesCount(); i++) {
          if (!getObjectProperties(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              category_ = input.readBytes();
              break;
            }
            case 34: {
              fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto.Builder subBuilder = fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addObjectProperties(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // required string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional string category = 3 [default = "default"];
      private java.lang.Object category_ = "default";
      public boolean hasCategory() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getCategory() {
        java.lang.Object ref = category_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          category_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCategory(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        category_ = value;
        onChanged();
        return this;
      }
      public Builder clearCategory() {
        bitField0_ = (bitField0_ & ~0x00000004);
        category_ = getDefaultInstance().getCategory();
        onChanged();
        return this;
      }
      void setCategory(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        category_ = value;
        onChanged();
      }
      
      // repeated .ObjectPropertyProto objectProperties = 4;
      private java.util.List<fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto> objectProperties_ =
        java.util.Collections.emptyList();
      private void ensureObjectPropertiesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          objectProperties_ = new java.util.ArrayList<fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto>(objectProperties_);
          bitField0_ |= 0x00000008;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto, fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto.Builder, fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProtoOrBuilder> objectPropertiesBuilder_;
      
      public java.util.List<fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto> getObjectPropertiesList() {
        if (objectPropertiesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(objectProperties_);
        } else {
          return objectPropertiesBuilder_.getMessageList();
        }
      }
      public int getObjectPropertiesCount() {
        if (objectPropertiesBuilder_ == null) {
          return objectProperties_.size();
        } else {
          return objectPropertiesBuilder_.getCount();
        }
      }
      public fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto getObjectProperties(int index) {
        if (objectPropertiesBuilder_ == null) {
          return objectProperties_.get(index);
        } else {
          return objectPropertiesBuilder_.getMessage(index);
        }
      }
      public Builder setObjectProperties(
          int index, fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto value) {
        if (objectPropertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObjectPropertiesIsMutable();
          objectProperties_.set(index, value);
          onChanged();
        } else {
          objectPropertiesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setObjectProperties(
          int index, fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto.Builder builderForValue) {
        if (objectPropertiesBuilder_ == null) {
          ensureObjectPropertiesIsMutable();
          objectProperties_.set(index, builderForValue.build());
          onChanged();
        } else {
          objectPropertiesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addObjectProperties(fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto value) {
        if (objectPropertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObjectPropertiesIsMutable();
          objectProperties_.add(value);
          onChanged();
        } else {
          objectPropertiesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addObjectProperties(
          int index, fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto value) {
        if (objectPropertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObjectPropertiesIsMutable();
          objectProperties_.add(index, value);
          onChanged();
        } else {
          objectPropertiesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addObjectProperties(
          fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto.Builder builderForValue) {
        if (objectPropertiesBuilder_ == null) {
          ensureObjectPropertiesIsMutable();
          objectProperties_.add(builderForValue.build());
          onChanged();
        } else {
          objectPropertiesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addObjectProperties(
          int index, fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto.Builder builderForValue) {
        if (objectPropertiesBuilder_ == null) {
          ensureObjectPropertiesIsMutable();
          objectProperties_.add(index, builderForValue.build());
          onChanged();
        } else {
          objectPropertiesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllObjectProperties(
          java.lang.Iterable<? extends fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto> values) {
        if (objectPropertiesBuilder_ == null) {
          ensureObjectPropertiesIsMutable();
          super.addAll(values, objectProperties_);
          onChanged();
        } else {
          objectPropertiesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearObjectProperties() {
        if (objectPropertiesBuilder_ == null) {
          objectProperties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          objectPropertiesBuilder_.clear();
        }
        return this;
      }
      public Builder removeObjectProperties(int index) {
        if (objectPropertiesBuilder_ == null) {
          ensureObjectPropertiesIsMutable();
          objectProperties_.remove(index);
          onChanged();
        } else {
          objectPropertiesBuilder_.remove(index);
        }
        return this;
      }
      public fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto.Builder getObjectPropertiesBuilder(
          int index) {
        return getObjectPropertiesFieldBuilder().getBuilder(index);
      }
      public fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProtoOrBuilder getObjectPropertiesOrBuilder(
          int index) {
        if (objectPropertiesBuilder_ == null) {
          return objectProperties_.get(index);  } else {
          return objectPropertiesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProtoOrBuilder> 
           getObjectPropertiesOrBuilderList() {
        if (objectPropertiesBuilder_ != null) {
          return objectPropertiesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(objectProperties_);
        }
      }
      public fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto.Builder addObjectPropertiesBuilder() {
        return getObjectPropertiesFieldBuilder().addBuilder(
            fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto.getDefaultInstance());
      }
      public fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto.Builder addObjectPropertiesBuilder(
          int index) {
        return getObjectPropertiesFieldBuilder().addBuilder(
            index, fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto.getDefaultInstance());
      }
      public java.util.List<fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto.Builder> 
           getObjectPropertiesBuilderList() {
        return getObjectPropertiesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto, fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto.Builder, fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProtoOrBuilder> 
          getObjectPropertiesFieldBuilder() {
        if (objectPropertiesBuilder_ == null) {
          objectPropertiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto, fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProto.Builder, fr.kissy.banshee.proto.ObjectPropertyDto.ObjectPropertyProtoOrBuilder>(
                  objectProperties_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          objectProperties_ = null;
        }
        return objectPropertiesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:ObjectProto)
    }
    
    static {
      defaultInstance = new ObjectProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ObjectProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ObjectProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ObjectProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030Proto/Debug/Object.proto\032 Proto/Debug/" +
      "ObjectProperty.proto\"r\n\013ObjectProto\022\n\n\002i" +
      "d\030\001 \002(\t\022\014\n\004name\030\002 \002(\t\022\031\n\010category\030\003 \001(\t:" +
      "\007default\022.\n\020objectProperties\030\004 \003(\0132\024.Obj" +
      "ectPropertyProtoB&\n\026fr.kissy.banshee.pro" +
      "toB\tObjectDTO\210\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ObjectProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ObjectProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ObjectProto_descriptor,
              new java.lang.String[] { "Id", "Name", "Category", "ObjectProperties", },
              fr.kissy.banshee.proto.ObjectDTO.ObjectProto.class,
              fr.kissy.banshee.proto.ObjectDTO.ObjectProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          fr.kissy.banshee.proto.ObjectPropertyDto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
